#!/usr/bin/env bash
set -euo pipefail

# ─── Step 9: Deploy Contracts to Chain ──────────────────────────────────────
#
# Usage: ./steps/09_deploy_chain.sh <project-name>
#
# Deploys contracts to the target chain and verifies them on the block explorer.
# Requires a funded deployer wallet.
#
# Inputs:
#   <project-name>  From params.json
#   Requires: ETH_PRIVATE_KEY or a generated deployer (yarn generate)
#   Reads: params.json for chain
#
# Outputs:
#   Deployed contract addresses
#   Updated deployedContracts.ts (auto-generated by SE2)
#   Verified source on block explorer
#
# Success: yarn deploy --network <chain> exits 0, contracts verified
# ─────────────────────────────────────────────────────────────────────────────

source "$(dirname "$0")/00_shared.sh"

PROJECT="${1:?Usage: ./steps/09_deploy_chain.sh <project-name>}"

load_params "$PROJECT"

echo ">>> Step 9: Deploying contracts to $CHAIN..."
echo "    Project: $PROJECT"
echo "    Chain:   $CHAIN (id: $CHAIN_ID)"
echo ""

cd "$PROJECT_DIR"

# ─── Ensure deployer is set up ───────────────────────────────────────────────
# If ETH_PRIVATE_KEY is in .env, import it. Otherwise check if one exists.
FOUNDRY_ENV="$PROJECT_DIR/packages/foundry/.env"

if [[ -n "${ETH_PRIVATE_KEY:-}" ]]; then
  echo "  Using ETH_PRIVATE_KEY from .env"
  # Write it to the foundry .env so deploy scripts can read it
  if [[ -f "$FOUNDRY_ENV" ]]; then
    # Update existing
    if grep -q "DEPLOYER_PRIVATE_KEY" "$FOUNDRY_ENV"; then
      sed -i.bak "s|DEPLOYER_PRIVATE_KEY=.*|DEPLOYER_PRIVATE_KEY=$ETH_PRIVATE_KEY|" "$FOUNDRY_ENV"
    else
      echo "DEPLOYER_PRIVATE_KEY=$ETH_PRIVATE_KEY" >> "$FOUNDRY_ENV"
    fi
  else
    echo "DEPLOYER_PRIVATE_KEY=$ETH_PRIVATE_KEY" > "$FOUNDRY_ENV"
  fi
  rm -f "$FOUNDRY_ENV.bak"
else
  echo "  No ETH_PRIVATE_KEY found. Checking for existing deployer..."
  if [[ -f "$FOUNDRY_ENV" ]] && grep -q "DEPLOYER_PRIVATE_KEY" "$FOUNDRY_ENV"; then
    echo "  Found existing deployer key in packages/foundry/.env"
  else
    echo "  Generating new deployer account..."
    yarn generate 2>&1 | tail -5
    echo ""
    echo "  ⚠ New deployer generated. You need to fund it before deploying."
    echo "  Run: yarn account  (to see the address)"
    echo "  Then send ETH to that address on $CHAIN."
    exit 1
  fi
fi

# ─── Add RPC override if we have one ────────────────────────────────────────
if [[ -n "${BASE_RPC_URL:-}" && "$CHAIN" == "base" ]]; then
  echo "  Using BASE_RPC_URL from .env"
  # Add to foundry.toml if not already there
  FOUNDRY_TOML="$PROJECT_DIR/packages/foundry/foundry.toml"
  if ! grep -q "$BASE_RPC_URL" "$FOUNDRY_TOML" 2>/dev/null; then
    sed -i.bak "s|base = .*|base = \"$BASE_RPC_URL\"|" "$FOUNDRY_TOML"
    rm -f "$FOUNDRY_TOML.bak"
  fi
fi

# ─── Deploy ──────────────────────────────────────────────────────────────────
echo ""
echo "  Deploying to $CHAIN..."
DEPLOY_OUTPUT=$(yarn deploy --network "$CHAIN" 2>&1) || true

if echo "$DEPLOY_OUTPUT" | grep -q "error\|Error\|FAIL"; then
  echo "  ✗ Deployment failed"
  echo "$DEPLOY_OUTPUT" | tail -20
  exit 1
fi

echo "$DEPLOY_OUTPUT" | tail -10
echo ""
echo "  ✓ Deployment succeeded"

# ─── Verify contracts ────────────────────────────────────────────────────────
echo ""
echo "  Verifying contracts on block explorer..."
VERIFY_OUTPUT=$(yarn verify --network "$CHAIN" 2>&1) || true
echo "$VERIFY_OUTPUT" | tail -10

# Verification is best-effort — don't fail the step if it doesn't work
if echo "$VERIFY_OUTPUT" | grep -qi "successfully verified\|already verified"; then
  echo ""
  echo "  ✓ Contracts verified"
else
  echo ""
  echo "  ⚠ Verification may have failed — check block explorer manually"
fi

# ─── Check deployedContracts.ts was updated ──────────────────────────────────
DEPLOYED_TS="$PROJECT_DIR/packages/nextjs/contracts/deployedContracts.ts"
if [[ -f "$DEPLOYED_TS" ]] && grep -q "$CHAIN_ID" "$DEPLOYED_TS"; then
  echo "  ✓ deployedContracts.ts updated with chain $CHAIN_ID"
else
  echo "  ⚠ deployedContracts.ts may not have been updated"
fi

echo ""
echo ">>> Step 9 complete."
